### ISSUE TITLE
ArgumentException with example code

### ISSUE THREAD

**Issue by slimshader** [Cysharp/MasterMemory#2]
Hi,

I just created fresh project in Unity 5.5, with empty GO and MB attached (in zip). This results in exception:

ArgumentException: does not implement right interface
System.Collections.Generic.Comparer`1+DefaultComparer[ZeroFormatter.KeyTuple`2[Gender,System.Int32]].Compare (KeyTuple`2 x, KeyTuple`2 y) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:771)
System.Array.compare[KeyTuple`2] (KeyTuple`2 value1, KeyTuple`2 value2, IComparer`1 comparer) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:319)
System.Array.qsort[KeyTuple`2,Person] (ZeroFormatter.KeyTuple`2[] keys, .Person[] items, Int32 low0, Int32 high0, IComparer`1 comparer) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:619)
System.Array.Sort[KeyTuple`2,Person] (ZeroFormatter.KeyTuple`2[] keys, .Person[] items, Int32 index, Int32 length, IComparer`1 comparer) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:303)
Rethrow as InvalidOperationException: The comparer threw an exception.
System.Array.Sort[KeyTuple`2,Person] (ZeroFormatter.KeyTuple`2[] keys, .Person[] items, Int32 index, Int32 length, IComparer`1 comparer) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:303)
MasterMemory.Memory`2[ZeroFormatter.KeyTuple`2[Gender,System.Int32],Person].FastSort (IEnumerable`1 datasource, System.Func`2 indexSelector, IComparer`1 comparer) (at Assets/MasterMemory/Memory.cs:360)
MasterMemory.Memory`2[ZeroFormatter.KeyTuple`2[Gender,System.Int32],Person]..ctor (IEnumerable`1 datasource, System.Func`2 indexSelector, Boolean rootMemory) (at Assets/MasterMemory/Memory.cs:87)
MasterMemory.Memory`2[ZeroFormatter.KeyTuple`2[Gender,System.Int32],Person]..ctor (IEnumerable`1 datasource, System.Func`2 indexSelector) (at Assets/MasterMemory/Memory.cs:77)
MemoryTesting.Start () (at Assets/MemoryTesting.cs:71)

I am using unitypackage from releases for MasterMemory (0.1.0) and binary (dll) releases for ZeroFormatter (1.6.0)

[MemoryTesting.zip](https://github.com/neuecc/MasterMemory/files/721156/MemoryTesting.zip)

**Comment by neuecc** [comment]
Thank you for testing!
Are you generated comparers from `MasterMemory.CodeGenerator.exe`?
https://github.com/neuecc/MasterMemory#unity-supports

and we needs `MasterMemoryHintAttribute` (sorry, currenly undocumented feature) on top of file.

```csharp
[assembly: MasterMemoryHint(typeof(Person), typeof(int), typeof(KeyTuple<Gender, int>))]
```

sorry, I needs to write more document.

**Comment by slimshader** [comment]
To be honest I am not sure what I should generate. I am testing for Windows platform so I should not be affected by IL2CPP issue, right?

It is a pleasure to test your stuff :)

**Comment by neuecc** [comment]
I need to make three pattern

* for .NET, .NET Core - it allows .NET 4.5 API
* for Unity(not IL2CPP) - it allows dynamic code generation
* for Unity(IL2CPP) - require pre code generation

However, due to share of the code, now Unity is only IL2CPP (ZeroFormatter is also the same reason).
