### ISSUE TITLE
Request: Use Semantic Versioning

### ISSUE THREAD

**Issue by aki017** [Cysharp/MasterMemory#20]
Semantic Versioning is a widely used convention in software development, distribution, and deployment.
I propose that MasterMemory adopt the semantic versioning conventions for future releases. If there are good reasons for not adopting this convention, MasterMemory should adopt a release labelling scheme that cannot be mistaken for semantic versioning.

**Comment by neuecc** [comment]
Currently major is following, but yes, minor and patch do not follow.
Ok, I'll try it.
