### ISSUE TITLE
EF Core support

### ISSUE THREAD

**Issue by Suriman** [Cysharp/MasterMemory#23]
Do you have plans to support Microsoft Entity Framawork Core?

**Comment by neuecc** [comment]
I don't know what you want.

**Comment by Suriman** [comment]
Sorry. EF Core has providers for each database engine supported. These providers are responsible for adapting the EF Core queries that are agnostic to the database engine to each of the supported database dialects. The question is about whether you have plans to implement a provider for MasterMemory.

**Comment by neuecc** [comment]
There is no plan at all.
The abstraction layer is unnecessary for 100% performance.
Also, the database provided by MasterMemory is different from what a general database requires.

**Comment by Suriman** [comment]
Thank you very much for the clarification.
