### ISSUE TITLE
Share db between applications

### ISSUE THREAD

**Issue by minhhungit** [Cysharp/MasterMemory#25]
Hi team, firstly this is awesome!

I have a question: I want to share database between 2 or more application, can I do that

I guess maybe I need a **_connectionstring_** or an address to make my applications understand where database is.

Have we support it yet or any road map for it

Thank you

**Comment by neuecc** [comment]
You can share only a file(path) simply, no need to connection-string.
Because data is read-only, can share.

For example, three projects
- DatabaseDefinition(MasterMemory)
- ProjectA(reference Database Definition)
- ProjectB(reference Database Definition)

ProjectA open database(File.ReadAllBytes(path)).
ProjectB open database(File.ReadAllBytes(path)).

**Comment by minhhungit** [comment]
yeah, thanks @neuecc , that is an option
but I think it's file-physical database, not "in-memory" right

**Comment by neuecc** [comment]
?
No, where come from data?
Data is persisted on disk(or sent from network or others).

**Comment by minhhungit** [comment]
I though we can build data from a array, something like this:

![image](https://user-images.githubusercontent.com/2279508/62100243-21f76280-b2bb-11e9-94b7-63fd3eebf64b.png)

and I am going to get those records from another application, can I ?

**Comment by minhhungit** [comment]
it looks I have to
- create db physical file from array which was build from c# entities  (List<Person>)
- from another application, access the physical file to get records

**Comment by neuecc** [comment]
MasterMemory's database data is store in the application's memory heap and can not share it between application.

It is easiest to share data via physical disk, but if you want to avoid use file, you can use MemoryMappedFile.
https://docs.microsoft.com/en-us/dotnet/api/system.io.memorymappedfiles.memorymappedfile.createnew

Or you may send data by IPC.

**Comment by minhhungit** [comment]
@neuecc thank you for your suggestion, I will check it
