### ISSUE TITLE
Null string check missing

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [Cysharp/MasterMemory#28]
I have started testing MasterMemory and while testing different modification of my models structures - to ensure it supports all possible modification, I came across a null string being read and sent to string.Intern making building the database impossible.

In InternStringResolver, there is no null check to the string that is sent to string.Intern.
Adding the null check didn't seem to cause any problem.

**Comment by neuecc** [comment]
Thanks, you're right!
I've fixed this issue and released `Ver 1.2.3`.
