### ISSUE TITLE
RangeView to implement ICollection ?

### ISSUE THREAD

**Issue by ttermeer-reboundcg** [Cysharp/MasterMemory#45]
I do not know if this is a good idea, but wouldn't it be better for RangeView to implement ICollection ? It already has a count method. This would improve performance when using Linq on RangeView as a IEnumerable.
This is useful for framework that needs abstraction.

**Comment by neuecc** [comment]
Thanks, I've checked discussions, IReadOnlyCollection is unlikely to be respect in the future.
https://github.com/dotnet/corefx/pull/28472
https://github.com/dotnet/runtime/issues/24793
Indeed, it seems better to implement.

**Comment by neuecc** [comment]
I've released 2.1.1, it includes this fix. thanks!
