### ISSUE TITLE
Is FindClosestBy returning wrong results?

### ISSUE THREAD

**Issue by atresnjo** [Cysharp/MasterMemory#49]
Hey, thanks for your amazing work as usual. I wanted to test if the library might work out for my use case, but right now I'm not getting the result returned that I expected.  Basically I expected it to find the person object with firstname == "realname" but I got the different one. Is this expected behavior? Thanks for your help! 

![grafik](https://user-images.githubusercontent.com/41112852/76077906-dff57400-5fa1-11ea-8090-14f5ff40f18a.png)

  ```
    [MemoryTable("people"), MessagePackObject(true)]
    public class PersonModel
    {
        [SecondaryKey(0), NonUnique]
        [SecondaryKey(1, keyOrder: 1), NonUnique]
        public string LastName { get; set; }

        [SecondaryKey(2), NonUnique]
        [SecondaryKey(1, keyOrder: 0), NonUnique]
        public string FirstName { get; set; }

        [PrimaryKey] public string RandomId { get; set; }
    }
```

**Comment by neuecc** [comment]
Comparing string is simple ordinal or current culture(in tuple).
This comparison is simply not found, just getting the lower.

**Comment by atresnjo** [comment]
> 
> 
> Comparing string is simple ordinal or current culture(in tuple).
> This comparison is simply not found, just getting the lower.

Ah, thanks. That works. Is there a way to use MasterMemory to return multiple results based on the comparison? If possible I would like to achieve something like:

```
        [Fact]
        public void Issue49()
        {
            var builder = new DatabaseBuilder().Append(new[]
            {
                new PersonModel {FirstName = "findname", LastName = "findlastname"},
                new PersonModel {FirstName = "findname1", LastName = "findlastname1"},
                new PersonModel {FirstName = "dontfind", LastName = "dontfind"},
            });

            var data = builder.Build();
            var database = new MemoryDatabase(data);

            var entries = database.PersonModelTable.FindClosestByFirstNameAndLastName(("find", "find"), false);

            // entries[0] == findname
            // entries[1] == findname1
            // entries[2] == dontfind

            entries.Count.Should().Be(3);
            entries.First.FirstName.Should().BeEquivalentTo("findname");
            entries.Last.FirstName.Should().BeEquivalentTo("dontfind");
        }

```

**Comment by neuecc** [comment]
Maybe your expectation is sql's like search,
but MasterMemory can not do it.

**Comment by atresnjo** [comment]
> 
> 
> Maybe your expectation is sql's like search,
> but MasterMemory can not do it.

Okay, thanks for the great work! Really impressive.
