### ISSUE TITLE
Is this a good use case for MasterMemory?

### ISSUE THREAD

**Issue by JesseTG** [Cysharp/MasterMemory#70]
I'm considering using MasterMemory for some of my Unity game's save data, but I'd like to ask about my use case to make sure I understand what this library is designed for.

Here are some facts about my game's data:

- I am using [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp) for serialization.
- I do not intend to use MasterMemory for game design assets (e.g. difficulty, level design, game mechanics); for that I will just use standard `ScriptableObject`s and prefabs.
- Most of my game's save data is only loaded once at the start of the game. This data is used every couple of minutes.
- Part of my game's save data consists of local leaderboards for each game mode that are updated with one entry at a time whenever the player finishes a session. When that happens (usually once every few minutes), the data is saved to disk.
- My game will have online leaderboards, but I haven't yet decided how it will be managed or structured.
- Another part of my game's save data consists of input configuration, which is fairly complicated due to the nature of the input manager I use. This data is referenced whenever a controller is connected, disconnected, or assigned to a player. It is modified whenever the player customizes their controls (very rare) or when the player is assigned a controller (more common).

Given this information, do you believe MasterMemory would be well-suited for my game?

**Comment by JesseTG** [comment]
Hi there, do you have any thoughts on this matter?

**Comment by neuecc** [comment]
Thanks for considering it.
However, here is not a free consulting room.

**Comment by JesseTG** [comment]
I guess this was a bigger question than I had anticipated. Thank you anyway. I look forward to using MasterMemory in my game.

**Comment by WithAnOrchid** [comment]
> * `ScriptableObject`s

I have the same concern, like do I really need it if I could just use `ReadOnlyCollection<T>`?
