### ISSUE TITLE
Dynamic Add From CSV

### ISSUE THREAD

**Issue by felixngd** [Cysharp/MasterMemory#75]
I can not find the method `builder.AppendDynamic` from generated code files. How can I fix it?

**Comment by arthurbla** [comment]
I also encountered that problem. I managed to find the given method in the source code of [Release 2.1.2](https://github.com/Cysharp/MasterMemory/releases/tag/2.1.2). Keep in mind that you need to set the runtime to .NET 4.X in order to use it.

**Comment by neuecc** [comment]
Sorry, lacked.
I've uploaded 2.4.3, it includes.
