### ISSUE TITLE
Need tutorial on how to use the latest version with Unity

### ISSUE THREAD

**Issue by TrongHieu90** [Cysharp/MasterMemory#92]
The lasted version 2.4.4 says it uses CodeGenerator supports net6.0
I managed to install the tool and this is the error
![image](https://github.com/Cysharp/MasterMemory/assets/20443445/9ba0be48-f39b-4340-ab30-510b3f3b14d6)

**Comment by Savidyaf** [comment]
I also didn't know this project is not compatible with newer C# versions. Hopefully they can update the documentation a bit

**Comment by neuecc** [comment]
v3.0.0 move to NuGet and Source Generator.
